// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc9UfHnwNMHJbTsp2svyyr_Tfz9ncLrUU',
    appId: '1:653846729459:web:8344f89e35fe80433b9d86',
    messagingSenderId: '653846729459',
    projectId: 'whatappapplicationflutter',
    authDomain: 'whatappapplicationflutter.firebaseapp.com',
    storageBucket: 'whatappapplicationflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGSPsmmQdzpOf9HrQxKDcZF3vgXCwXTA',
    appId: '1:653846729459:android:4b5f8458e39abf283b9d86',
    messagingSenderId: '653846729459',
    projectId: 'whatappapplicationflutter',
    storageBucket: 'whatappapplicationflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hywBJdXPSTR7vkdlH_RsA5WImh7nGB8',
    appId: '1:653846729459:ios:3e25ef22ce2baa193b9d86',
    messagingSenderId: '653846729459',
    projectId: 'whatappapplicationflutter',
    storageBucket: 'whatappapplicationflutter.appspot.com',
    iosBundleId: 'com.example.chattingmessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hywBJdXPSTR7vkdlH_RsA5WImh7nGB8',
    appId: '1:653846729459:ios:a03ab36837f8b3da3b9d86',
    messagingSenderId: '653846729459',
    projectId: 'whatappapplicationflutter',
    storageBucket: 'whatappapplicationflutter.appspot.com',
    iosBundleId: 'com.example.chattingmessaging.RunnerTests',
  );
}
